### ISSUE TITLE
Ajouter OpenFisca à la page des produits

### ISSUE THREAD

**Issue by sandcha** [incubateur-territoires/incubateur.anct.gouv.fr#17]
OpenFisca est très heureux d'arriver à l'incubateur mais le produit ne figure pas encore sur la page des services numériques 🙀 

@pichot Que conseillerais-tu pour y remédier ? 
Est-ce par la création d'une PR sur ce dépôt pour figurer sur [cette page](https://incubateur.anct.gouv.fr/services/) ? 
Ceci sachant qu'openfisca ne figure pas dans la liste des startups de beta.gouv.fr DINUM (en référence à l'issue #13).

**Comment by jdesboeufs** [comment]
OpenFisca est sur cette page : https://incubateur.anct.gouv.fr/actions/collaborations/

**Comment by sandcha** [comment]
Merci ! Cette issue est donc close 🙂
